Vagrant.configure(2) do |config|

  config.vm.box = "box-cutter/centos72"
  config.vm.box_version = "2.0.13"
  
  # Use the vagrant-cachier plugin, if installed, to cache downloaded packages
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.network "forwarded_port", guest: 3001, host: 3003
  config.vm.network "forwarded_port", guest: 3000, host: 9090
  config.vm.network "forwarded_port", guest: 8161, host: 8166

  config.vm.provider "virtualbox" do |vb|
   vb.gui = false
   vb.name = "oneops"
   vb.memory = 6144
   vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end

  config.vm.provision :shell, path: "oo-prereqs.sh"
  config.vm.provision :shell, path: "oo-setup.sh", env: {"OO_VALIDATION" => "false"}
end
